apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devsecops
  name: devsecops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops
  strategy: {}
  template:
    metadata:
      labels:
        app: devsecops
    spec:
      volumes:
      - name: vol
        emptyDir: {}
      - name: spring-config
        configMap:
          name: devsecops-config
      serviceAccountName: default
      automountServiceAccountToken: false
      containers:
      - image: DEPLOY_IMAGE
        name: devsecops-container
        volumeMounts:
        - mountPath: /tmp
          name: vol
        - name: spring-config
          mountPath: /config
        securityContext:
          runAsNonRoot: true
          runAsUser: 100
          readOnlyRootFilesystem: true
        env:
        - name: SPRING_CONFIG_LOCATION
          value: /config/application.properties
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: devsecops-config
data:
  application.properties: |
    server.port=8080
    base.url=BASE_URL
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: devsecops
  name: devsecops-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: devsecops
  type: NodePort